### ISSUE TITLE
feat: Criar Teste unitário para a classe de atributos

### ISSUE THREAD

**Issue by srgoogle23** [ecommercecpp/ecommercecpp#39]
Explicação do que é um teste unitário, eu mandei no grupo. Mas:
- Criei uma base para o teste unitário em [ecommercecpp](https://github.com/ecommercecpp/ecommercecpp)/[include](https://github.com/ecommercecpp/ecommercecpp/tree/main/include)/[unitTest](https://github.com/ecommercecpp/ecommercecpp/tree/main/include/unitTest)/unitTest.hpp 
- Para cada teste unitário, deverá ser estendido uma classe da classe base dando override na função run.
- Após isso, deverá ser criado um cpp dentro de [ecommercecpp](https://github.com/ecommercecpp/ecommercecpp)/[src](https://github.com/ecommercecpp/ecommercecpp/tree/main/src)/unitTest/ conforme o unitTestEndereco.cpp
- Toda a tentativa de código deverá se localizar dentro de um try {} e caso der erro, o código automaticamente irá para o catch{}.
- Para lançar uma exceção, ou seja, um erro que não era pra ter acontecido, use throw.
- Exemplo:
```cpp
void UnitTestExemplo::run()
{
	try
	{
		bool teste = false;
   		// seu código normal
		// ...
		// aqui, caso um valor não for true, lança um erro:
		if(teste == true)
		{
			throw std::runtime_error("a variável 'teste' não é true");
		}

		// caso passar em todos os testes, use pass(); para passar o teste
		pass();
	}
	catch ( std::exception &e )
	{
		fail(std::string(e.what()));
	}
}
```

**Comment by EduScf** [comment]
Vou tentar estressar mais
