### ISSUE TITLE
Validações no método de cadastro de usuário

### ISSUE THREAD

**Issue by srgoogle23** [ecommercecpp/ecommercecpp#50]
Dentro da classe `CLI`, no método `cadastro` e dentro da classe de `usuarios` no metodo `cadastro` precisamos que sejam feitas todas as validações necessárias para impedir o programa de parar de rodar.
Algumas que eu já pensei:
- Ta com um problema de que se eu digitar um inteiro onde ta como string, para o programa. Tu precisa verificar se o cara nao digitou uma palavra antes de atribuir no valor de um inteiro, como o cpf por exemplo.
- Validacao de tamanho de cpf
- validacao de tamanho de cep
- Validacao, nao permitir nenhum campo vazio
- fazer que, enquanto o usuario não digitar todos os campos corretamente ou digitar algum comando para voltar ao menu principal, nao saia do loop
- validar no arquivo de dados, ja nao foi carregado um usuario com o mesmo cpf ou com o mesmo email, caso acontecer informar pro usuario e reiniciar o cadastro
- todas as exceções devem ser lançadas no cadastro do usuario e serem tratados na classe de CLI

**Comment by EduScf** [comment]
Estou fazendo
