### ISSUE TITLE
Lógica de transformar o usuário em um administrador e outras validações

### ISSUE THREAD

**Issue by srgoogle23** [ecommercecpp/ecommercecpp#53]
Descreva dentro desse issue no minimo 5 maneiras diferentes que podemos implementar uma maneira para o cadastro para o login ( total 10) para definir um usuario como administrador ( meio que transformar um usuario comum em adm )

Validar todo o código ja construído na main, procurando erros no doxygen. Ver possiveis testes unitários usando valores para testar funcionalidades

**Comment by FelippeVelosoMarinho** [comment]
Possibilidades de implementação do cadastro para o login administrador.
- Inserir duas possiblidades de criação de conta/cadastro de usuário no loja.cpp. 
- Fazer com que o usuário comum também possa ter acesso às funções de um usuário ADM atrelada ao seu perfil de usuário comum. "Seriam os mesmo dados de conta, porém com as funções de ADM também, semelhante ao código de upgrade das cartas dado em sala."
Para isso é necessário a separação entre um usuário comum e ADM com as possíveis formas:

> - Criar simplesmente uma booleano no construtor da classe usuário e criar toda a lógica do ADM baseada em se a variável for true;
> - Fazer dois .hpp e .cpp para usuarioComum e usuarioAdm e utilizando a classe  usuario já feita como classe pai. Sendo assim as duas classes diferentes poderiam ter suas devidas diferenças e aproveitar características em comum de sua herança com a classe usario;
> - Criar na classe usuário, uma interface de níveis de usuários definidas por um enum semelhante ao exemplo dos níveis de acesso do moodle dado em sala de aula. Sendo assim teria que haver uma mudança no construtor, porém o código ficaria mais otimizável e organizado.
